let Products = [
    ['/model/KMODEL (1).png', 'White Shirt', 'Shirt', '25', 'DISCOUNT0', 'kids','PRIORITYF','PN001'],
    ['/model/KMODEL (2).png', 'White Jacket', 'Jacket', '45', 'DISCOUNT0', 'kids','PRIORITYF','PN002'],
    ['/model/KMODEL (3).png', 'Gray Shirt', 'Shirt', '30', 'DISCOUNT0', 'kids','PRIORITYF','PN003'],
    ['/model/KMODEL (4).png', 'Cotton Sweater', 'Sweater', '35', 'DISCOUNT0', 'kids','PRIORITYF','PN004'],
    ['/model/KMODEL (5).png', 'Black Cotton Hat', 'Hat', '5', 'DISCOUNT0', 'kids','PRIORITYF','PN005'],
    ['/model/KMODEL (6).png', 'Woven Cotton Hoodie ', 'Hoodie', '35', 'DISCOUNT0', 'kids','PRIORITYF','PN006'],
    ['/model/KMODEL (7).png', 'Dark Grey Hoodie', 'Hoodie', '30', 'DISCOUNT0', 'kids','slide1','PN007'],
    ['/model/FMODEL (1).png', 'White Sweat Shirt', 'Shirt', '35', 'DISCOUNT0', 'female','PRIORITYF','PN008'],
    ['/model/FMODEL (2).png', 'Black Sweat Shirt', 'Shirt', '30', 'DISCOUNT0', 'female','discount1','PN009'],
    ['/model/FMODEL (3).png', 'Red Long Sleeve Shirt', 'Shirt', '40', 'DISCOUNT0', 'female','slide2','PN010'],
    ['/model/FMODEL (4).png', 'Black Hoodie', 'Hoodie', '45', 'DISCOUNT0', 'female','PRIORITYF','PN011'],
    ['/model/FMODEL (5).png', 'Cotton Scarf', 'Scarf', '10', 'DISCOUNT0', 'female','PRIORITYF','PN012'],
    ['/model/FMODEL (6).png', 'Black Hat', 'Hat', '8', 'DISCOUNT0', 'female','PRIORITYF','PN013'],
    ['/model/FMODEL (7).png', 'Black n White Sweater', 'Sweater', '35', 'DISCOUNT0', 'female','PRIORITYF','PN014'],
    ['/MODEL6.PNG', 'Black Jacket', 'Jacket', '32', 'DISCOUNT0', 'female','main','PN015'],
    ['/model/MMODEL (1).png', 'Black Sweat Shirt', 'Shirt', '25', 'DISCOUNT0', 'male','PRIORITYF','PN016'],
    ['/model/MMODEL (2).png', 'Black Hat', 'Hat', '6', 'DISCOUNT0', 'male','PRIORITYF','PN017'],
    ['/model/MMODEL (3).png', 'Light Gray Jacket', 'Jacket', '50', 'DISCOUNT0', 'male','PRIORITYF','PN018'],
    ['/model/MMODEL (4).png', 'Dark Gray Jacket', 'Jacket', '45', 'DISCOUNT0', 'male','PRIORITYF','PN019'],
    ['/model/MMODEL (5).png', 'Gray Cotton Hoodie', 'Hoodie', '30', 'DISCOUNT0', 'male','slide3','PN020'],
    ['/model/MMODEL (6).png', 'Sweat Shirt', 'Shirt', '35', 'DISCOUNT0', 'male','discount3','PN021'],
    ['/model/MMODEL (7).png', 'White Jacket', 'Jacket', '50', 'DISCOUNT0', 'male','discount2','PN022'],
  ];

export default Products;